### PR TITLE
Bump utils to v 0.5.0

### PR DESCRIPTION
**Pull request by clrcrl**
## Description & motivation
Bumping the upper bound so that people can use the latest version of utils
Bumping the lower bound for consistency
Fixed tests so that we get ✅ 

## Checklist
- [x] I have verified that these changes work locally
- n/a I have updated the README.md (if applicable)
- n/a I have added tests & descriptions to my models (and macros if applicable)

### CODE REVIEW

**Comment by clrcrl** [comment]
@jtcohen6 — I updated some env vars in the `profiles.yml` to bring them into line with the other repos. But I think you might need to do some CircleCI config! Let me know if I should undo those changes :)

**Comment by clrcrl** [comment]
I noticed that this repo doesn't have a `.github` directory. Before we merge it, I'm going to add those :)

**Comment by clrcrl** [comment]
OK all we gotta do now is wait for us to be able to switch the default branch around 🤞

**Review by jtcohen6 — APPROVED** [review]
LGTM, pending branch switching

**Comment by clrcrl** [comment]
For posterity, we kept the current default branch due to downstream impacts on the hubcap script

**Pull request merged**
